version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "yarn.lock" }}
          - v2-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - ~/.cache/yarn
          key: v2-dependencies-{{ checksum "yarn.lock" }}
        
      - run: yarn run lint
      - run: yarn run test-ci

